[package]
name = "smeval"
version = "0.3.0"
authors = ["Joeyrp <jrpollack107@gmail.com>"]
edition = "2018"
description = "A Simple Math Evaluator. Based on this tutorial https://www.youtube.com/watch?v=tczjDCbykyM"

[dependencies]
